### ISSUE TITLE
Failures with Flarum BETA 6 

### ISSUE THREAD

**Issue by bikepost** [FriendsOfFlarum/analytics#11] opened 2017-07-10 18:55 UTC
Many thanks to @santiagobiali over on the Flarum forum pages.
Posting here after attempting to solve without success.

@luceos @jordanjay29 

Please let me know what I can do to help. 
Limited skill set here but I have spent quite some time on trying to get the extension to install properly with Flarum BETA 6. I am not sure whether anyone has it working. @luceoas mentioned higher up (Oct 2016) that it had been updated to work with Flarum BETA 6.

Here are my steps and it failed each time (so I can reproduce):

1. Installed Piwik 3.0.4 with a one-click Softaculous host install. Piwki URL: http://bikepost.cc/analytics
2. Used
[code]composer require flagrow/flarum-ext-analytics[/code]
[code]php flarum cache:clear[/code]

3. Analytics then is visible under the Flarum Admin page and enabling it (checking the check box) opens a pop-up window but its appearance is broken. I filled it out anyway, at that point the extension does get added to the left admin pane but it can't load the page.

See screenshots and details below.
(I have removed the extension and deleted the Piwik install after taking these screenshots).

Details:
Pointing to https://bikepost.cc/analytics
Table 1
Authentication Code (copied and pasted from the Piwik admin page under API)

NOTE:
After unchecking the Analytics check box under Extension, the option to uninstall becomes avail but doesn't work (see last screenshot). 
To remove it I have to use composer:

[code]composer remove flagrow/flarum-ext-analytics[/code]
[code]php flarum cache:clear[/code]

Screenshots:

![](https://content.screencast.com/users/sl972/folders/Default/media/4b6be9c5-d1e3-4414-98f5-c4c20948de93/A.png)

![](https://content.screencast.com/users/sl972/folders/Default/media/f62b0472-f706-4ccc-9088-b2c4b3f18357/B.png)

![](https://content.screencast.com/users/sl972/folders/Default/media/ddda777c-5e6d-4a77-9d81-c186eda11075/C.png)

![](https://content.screencast.com/users/sl972/folders/Default/media/0dccbbd2-2ffc-4fc2-9e3a-884475450084/D.png)

![](https://content.screencast.com/users/sl972/folders/Default/media/7dc5dc2a-bc21-4115-9367-473dce0b0520/E.png)

![](https://content.screencast.com/users/sl972/folders/Default/media/2a7da8b7-400c-4d7d-9fd2-0de1201de5c6/F.png)

The browser console shows error:
[code]Failed to load resource: net::ERR_CONNECTION_REFUSED[/code]

Even after performing following these instructions: https://piwik.org/faq/troubleshooting/faq_147/

My host uses apache servers so I couldn't follow the instructions here:
https://serverfault.com/questions/801651/nginx-x-frame-options-iframe-wordpress

**Comment by clarkwinkelmann** [comment] 2017-12-06 16:02
I'm just noticing this issue is still open. Was it resolved outside of the tracker (maybe with @luceos ?) or are you still seeking help ?

I'm sorry if we forgot to follow up.

**Comment by luceos** [comment] 2017-12-07 10:54
@clarkwinkelmann I haven't given the analytics extension any attention it deserved. @bikepost I'm sorry I forgot about you.

**Comment by Benoit1980** [comment] 2018-06-03 14:32
same problem here, blank screen on the latest Flarum version

**Comment by clarkwinkelmann** [comment] 2018-06-04 12:01
@FreddyCrugger are you sure it's the same issue ? I see no mention of blank screen in the original report.

Could you try clearing your Flarum and browser cache and see if this persists ?

If you still experience it could you open another issue with a more detailed explanation of what you did / try to do ? Thanks.

**Comment by Benoit1980** [comment] 2018-06-04 13:27
Hi Yes the cache cleanup was done via SSH. No worry, as I could not get it going I install google analytics in cloudflare, all good now. I think it is better not to use too many plugins as they seem to break a lot on updates so I will try to stay away from the, until the version is fully stable. thanks again for your help.

**Comment by clarkwinkelmann** [comment] 2020-03-11 02:16
I will close this issue because it was for an older version of Flarum and the extension.

Feel free to open a new issue with a fresh `php flarum info` and steps to reproduce if you still experience problems.

**Closed as completed by clarkwinkelmann** 2020-03-11 02:16 UTC
